### PR TITLE
changed the transition to search icon

### LINKED ISSUE #1: Search transition and color
when hovering the mouse on search icon in the header the icons does not have transition and change color

Screenshot 2024-09-06 171933

### PR DESCRIPTION
**Pull request by Rahul-2006**
Fixes: #1

### CODE REVIEW

**Comment by Rahul-2006** [comment]
Hi @ehsanullahhaidary 
can you please see it now and tell me if there is any other issues

**Comment by successbyte** [comment]
thanks @Rahul-2006 
the PR merged

**Comment by Rahul-2006** [comment]
Thank you for merging it @ehsanullahhaidary 
It is my first official open source contribution which got merged
Thanks a lot

**Comment by successbyte** [comment]
Congrats bro 🥳

**Review by successbyte — COMMENTED** [review]
good

**Pull request merged**
