### PR TITLE
add darker color transition on hover

### LINKED ISSUE #7: Add transition to sign in button
Add a transition to sign in button when hover 

it should change it's color to more grayish (dark gray) when hover mouse over it

Screenshot 2024-09-08 105733

### PR DESCRIPTION
**Pull request by Punith1117**
for sign-in button

Fixes #7

### CODE REVIEW

**Comment by successbyte** [comment]
Hi @Punith1117 thanks for PR
I merged your PR but try these next time:
- first ask the maintainer to assign you to the issue
- in the PR have something to close the issue ex: Fixes #number-of-issue

**Comment by successbyte** [comment]
@Punith1117 tell all your beginner friends 
this repo is welcomed for any first-timer to create issue, feature, improvements and PR

**Comment by Punith1117** [comment]
Hi @ehsanullahhaidary.

Thanks for the advice. I will keep them in mind for future contributions.

**Comment by successbyte** [comment]
Great @Punith1117

**Review by successbyte — COMMENTED** [review]
good

**Comment by successbyte** [comment]
Hi @Punith1117  
could you please give the repo a star.

**Comment by Punith1117** [comment]
Sure. I did it right now. Sent from Mail for Windows 10 From: Ehsan HaidarySent: 15 September 2024 07:34To: successbyte/dribble-cloneCc: Punith1117; MentionSubject: Re: [successbyte/dribble-clone] add darker color transition on hover (PR #8) Hi @Punith1117could you please give the repo a star.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Pull request merged**
