### PR TITLE
Selected text color and its background color changed to desired colors

### LINKED ISSUE #9: Selected text color
# New Issue
The selected text color is somehow pink and I want it to be changes to a blue color with a little opacity 
ex: when selecting a the text color should be `#e0e0e0` and the background color should be `#2782b382`

## Actual behavior

Screenshot 2024-09-10 220412

## Expected behavior

Screenshot 2024-09-10 222030

### PR DESCRIPTION
**Pull request by Pranathi1314**
Resolves #9
The selected text and its background color was required to be changed to #e0e0e0 and #2782b382 respectively. Hence I have made the desired changes in the  variables scss file for it. The project works fine on my PC after the changes made as seen in the screen shot below : 
scss

### CODE REVIEW

**Review by successbyte — APPROVED** [review]
it's great thanks

**Comment by successbyte** [comment]
Hi @Pranathi1314 would you please give the repo a star

**Comment by Pranathi1314** [comment]
> Hi @Pranathi1314 would you please give the repo a star
I already have 👍

**Comment by successbyte** [comment]
thanks bro

**Pull request merged**
